name: Release Obsidian plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Fetch the latest draft release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_draft_release=$(curl -H "Authorization: token $GITHUB_TOKEN" \
                                     -H "Accept: application/vnd.github+json" \
                                     "https://api.github.com/repos/${{ github.repository }}/releases" \
                                     | jq -r '.[] | select(.draft == true) | .tag_name' | head -n 1)
          echo "Latest draft release tag: $latest_draft_release"
          if [ -z "$latest_draft_release" ]; then
            echo "No draft release found. Exiting..."
            exit 1
          fi

      - name: Upload assets to the latest draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$latest_draft_release" main.js manifest.json styles.css
