name: Release Obsidian plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Upload assets to the latest draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_draft_tag=$(gh release list --limit 1 --draft | cut -f3)
          echo "Latest draft release tag: $latest_draft_tag"
          if [ -z "$latest_draft_tag" ]; then
            echo "No draft release found. Exiting..."
            exit 1
          fi
          gh release upload "$latest_draft_tag" main.js manifest.json styles.css
