name: Release Obsidian plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Fetch the latest draft release tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          draft_release=$(gh release list --limit 1 --draft | cut -f3)
          echo "Draft release tag: $draft_release"
          if [ -z "$draft_release" ]; then
            echo "No draft release found. Exiting..."
            exit 1
          fi
          echo "DRAFT_TAG=$draft_release" >> $GITHUB_ENV

      - name: Echo the draft release tag (for debugging)
        run: echo "Using draft tag: $DRAFT_TAG"

      - name: Upload assets to the draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "$DRAFT_TAG" main.js manifest.json styles.css
